In [1]:
import numpy as np

In [2]:
vector = np.array(range(3,27))

In [3]:
vector

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26])

In [5]:
vector2 = np.array([0,1,2,3,4,0,1,2,3,4])

In [6]:
vector2

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [7]:
vector2.sort()

In [8]:
vector2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])